language: cpp
sudo: required
dist: serena

branches:
  only:
    - master
    - "/^v\\d+\\./"
script: ./build/linux_build

matrix:
  include:
  - os: linux
    compiler: clang-6.0
    addons:
      apt:
        packages:
          - g++-7
          - clang-6.0
          - libgl1-mesa-dev
          - libegl1-mesa-dev
          - libgles2-mesa-dev
          - libxcb-util0-dev
          - libxcb-image0-dev
    before_install:
      - sudo apt-get update
      - sudo apt-get purge cmake
      - version=3.13
      - build=3
      - mkdir ~/temp
      - cd ~/temp
      - wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
      - tar -xzvf cmake-$version.$build.tar.gz
      - cd cmake-$version.$build/
      - ./bootstrap
      - make
      - sudo make install --silent
