language: cpp
sudo: required
dist: trusty

branches:
 only:
 - master
 - "/^v\\d+\\./"
script: ./build/linux_build

matrix:
 include:
  - os: linux
    compiler: clang-6.0
    addons:
        apt:
          packages:
            - clang-6.0
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
