language: cpp
sudo: required
dist: serena

branches:
  only:
    - master
    - "/^v\\d+\\./"
script: ./build/linux_build

matrix:
  include:
  - os: linux
    compiler: clang-6.0
    addons:
      apt:
        packages:
          - clang-6.0
          - libgl1-mesa-dev
          - libegl1-mesa-dev
          - libgles2-mesa-dev
          - libxcb-util0-dev
          - libxcb-image0-dev
    before_install:
      - cmake --version
      - sudo apt-get update
      - sudo apt remove --purge --auto-remove -y cmake
      - cmake --version
      - version=3.13
      - build=3
      - mkdir ~/temp
      - pushd ~/temp
      - wget https://cmake.org/files/v$version/cmake-$version.$build-Linux-x86_64.sh
      - tar -xzf cmake-$version.$build-Linux-x86_64.tar.gz
      - sudo mkdir /opt/cmake
      - sudo sh cmake-$version.$build-Linux-x86_64.sh --prefix=/opt/cmake
      - pushd cmake-$version.$build-Linux-x86_64/
      - popd
      - popd
      - sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
      - rm -r /temp
      - cmake --version
