language: cpp
sudo: required
dist: trusty
compiler:
 - clang
os:
 - linux
ruby: 2.2.0
before_install:
 - sudo apt-get update
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
 - sudo apt-get install build-essential
 - sudo apt-get purge cmake
 - version=3.13
 - build=3
 - mkdir ~/temp
 - cd ~/temp
 - wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
 - tar -xzvf cmake-$version.$build.tar.gz
 - cd cmake-$version.$build/
 - ./bootstrap
 - make
 - sudo make install
branches:
 only:
 - master
 - "/^v\\d+\\./"
script: ./build/linux_build
